@startuml Auth
skinparam classAttributeIconSize 0
left to right direction

class Fields {
	-name: string
	-degree: string
}

class Picker
class Button
class TextInput
class PasswordInput
class Link
class Text 
enum User {
	STUDENT,
	PROFESSOR
}

class RegisterScreen {
	-mail: string
	-password: string
	-passwordConfirm: string
	-error: string

	-fetch(): Promise
	-study(): number
	-type(): User
	-valid(): boolean
	-degrees(): string
	-register(): void

	-setMail(): void
	-setPassword(): void
	-setPasswordConfirm(): void
	-setFOS(): void
	-setFields(): void
	-setError(): void
}

class Theme
class LoginScreen {
	-email: string
	-password: string
	-error: string
	-theme: Theme

	-login(): void
	
	-setToken(): void
	-setError(): void
	-setEmail(): void
	-setPassword(): void
}

Text --* Login
Text --* Register

Theme --* Login

User --* Register

TextInput --* Login
Button --* Login
Link --* Login
PasswordInput --* Login
PasswordInput --|> TextInput

TextInput --* Register
PasswordInput --* Register
Link --* Register
Button --* Register
Fields --* Register
Picker --* Register
@enduml
