@startuml 
skinparam classAttributeIconSize 0


abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  + Object[] elementData

  size()
  + getData(user)
}

enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}

annotation SuppressWarnings

annotation Annotation {
  annotation with members
  String foo()
  String bar()
}

annotation Annotation {
  annotation with members
  String foo()
  String bar()
}


annotation Annotationa {
  annotation with members
  String foo()
  String bar()
}


annotation Annotatioan {
  annotation with members
  String foo()
  String bar()
}



@enduml