# @author Kiran Singh
version: "3.7"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stunet
    ports:
      - '5432:5432'
    volumes:
      - stunet-db:/var/lib/postgresql/data
    networks:
      - mynet

  api:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - mynet

volumes:
    stunet-db:
    portainer_data:

networks:
  mynet:
    driver: bridge
    # ipam:
    #   driver: default
