@startuml Ask question

title Reference: [Contract] SubmitQuestion

participant ":QuestionController" as controller
participant ":UserManager" as userManager
participant ":QuestionSubscription" as questionSubscription
participant ":QuestionNotification" as questionNotification
participant ":Question" as question
participant GetQuestionDto
participant ":GetQuestionDto" as getQuestionDto
participant ":CourseRepository" as courseRepository
participant ":TopicRepository" as topicRepository
participant ":QuestionRepository" as repository
participant ":QuestionSubscriptionRepository" as questionSubscriptionRepository
participant ":CourseSubscriptionRepository" as courseSubscriptionRepository
participant ":NotificationRepository" as notificationRepository

-> controller: CreateQuestion(createQuestionDto)
activate controller

alt Valid user
    controller -> userManager: FindByEmailAsync(userEmail)
    activate userManager
    controller <-- userManager: User
    ' TOASK: User|null of gewoon User?
    deactivate userManager

    controller -> courseRepository: GetAsync(createQuestionDto.courseId)
    activate courseRepository
    courseRepository --> controller: Course | null
    deactivate courseRepository

    loop createQuestionDto.topicIds
        controller -> topicRepository: GetAsync(id)
        activate topicRepository
        topicRepository --> controller: Topic | null
        deactivate topicRepository
    end

    alt Course in the database AND All topicss in database
        controller -> question **:create(createQuestionDto.title, user.id, course, createQuestionDto.body, topics, DateTime.UtcNow)

        controller -> repository: CreateAsync(question)
        activate repository
        repository --> controller: void
        deactivate repository

        controller -> questionSubscription **:create(user.id, question.id, question.time)

        controller -> questionSubscriptionRepository: CreateAsync(questionSubscription)
        activate questionSubscriptionRepository
        questionSubscriptionRepository -> controller: void
        deactivate questionSubscriptionRepository

        loop
            controller -> courseSubscriptionRepository: GetByCourseId(course.id)
            activate courseSubscriptionRepository
            courseSubscriptionRepository --> controller: SubscriberId
            deactivate courseSubscriptionRepository
        end

        loop
            controller -> questionNotification**: create(userId, question.id, question, question.time)
        end

        controller -> notificationRepository: CreateAllAync(questionNotifications)
        activate notificationRepository
        notificationRepository --> controller: void
        deactivate notificationRepository

        controller -> GetQuestionDto: convert(question, user)
        activate GetQuestionDto
        GetQuestionDto -> getQuestionDto**: create(question, user)
        GetQuestionDto --> controller: returnDto
        deactivate GetQuestionDto

        <-- controller: returnDto
    else Course not in the database OR some topic not in database
        <-- controller: badRequeset
    end
else Invalid user
    <-- controller: unauthorized
end

deactivate controller

@enduml