@startuml Create course

title Reference: [Contract] SubmitCourse

participant ":CourseController" as controller
participant ":Course" as course
participant ":CourseRepository" as repository

--> controller: CreateCourse(dto.name, dto.number, dto.description,\n\tdto.courseEmail, dto.profEmail)
activate controller

alt Valid user
    controller -> course **: create(dto.name, dto.number, dto.description, dto.courseEmail, userEmail)
    
    controller -> repository: CreateAsync(course)
    activate repository
    repository --> controller: void
    deactivate repository

    <-- controller: ok
else Invalid user
    <-- controller: unauthorized
end

deactivate controller

@enduml