@startuml Search course

title Reference: [UC] Search Course

participant ":CourseController" as courseController
participant GetAllCourseDto
participant ":GetAllCourseDto" as getAllCourseDto
participant StringMatcher
participant ":CourseRepository" as courseRepository

-> courseController: SearchByName(name)
activate courseController

courseController -> courseController: _GetCourseAsync()
activate courseController

courseController -> courseRepository: GetAllAsync()
activate courseRepository
courseRepository --> courseController: courses
deactivate courseRepository

loop
    courseController -> GetAllCourseDto: convert(course)
    activate GetAllCourseDto
    GetAllCourseDto -> getAllCourseDto **: create(course)
    GetAllCourseDto --> courseController: courseDto
    deactivate GetAllCourseDto
end

courseController --> courseController: courseDtos
deactivate courseController

courseController -> StringMatcher: FuzzyMatchObject(courseDtos, name)
activate StringMatcher
StringMatcher --> courseController: matches
deactivate StringMatcher

alt searchResults not empty AND searchResults not all
    ' To-ASK
    <-- courseController: ok
else searchResults empty OR searchResults all
    <-- courseController: noContent
end