@startuml Search course

title Reference: [UC] Search Course

participant ":CourseController" as controller
participant GetAllCourseDto
participant ":GetAllCourseDto" as getAllCourseDto
participant StringMatcher
participant ":CourseRepository" as repository

-> controller: SearchByName(name)
activate controller

controller -> controller: _GetCourseAsync()
activate controller

controller -> repository: GetAllAsync()
activate repository
repository --> controller: courses
deactivate repository

loop
    controller -> GetAllCourseDto: convert(course)
    activate GetAllCourseDto
    GetAllCourseDto -> getAllCourseDto **: create(course)
    GetAllCourseDto --> controller: courseDto
    deactivate GetAllCourseDto
end

controller --> controller: courseDtos
deactivate controller

controller -> StringMatcher: FuzzyMatchObject(courseDtos, name)
activate StringMatcher
StringMatcher --> controller: matches
deactivate StringMatcher

alt searchResults not empty AND searchResults not all
    ' To-ASK
    <-- controller: ok
else searchResults empty OR searchResults all
    <-- controller: noContent
end