@startuml Send chat message

title Reference: [UC] Send Chat Message

participant ":ChatHub" as hub
participant ":Message" as message
participant ":MessageRepository" as repository

--> hub : SendMessageToChannel(\n\tmessage, channelId)
activate hub

hub -> message ** : create(userEmail, channelId, message, DateTime.UtcNow)

hub -> repository: CreateAsync(message)
activate repository
repository --> hub: void
deactivate repository

<-- hub: void

deactivate hub

@enduml