@startuml createCourseCompunentDiagram

component Accounting <<subsystem>>{
    port " " as port
    component ":Accounts" as Accounts
    component ":Courses" as Courses
    

}

component X {
    port " " as x_out
}
x_out -u0)- [Z]

@enduml